### ISSUE TITLE
Bug: Warning: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by rygine** [xmtp/proto#115]
### Describe the bug

While using the JS or React SDK the app functions as expected, but I receive a recurring error in the console regarding a missing file. The error is as follows:

![image](https://github.com/xmtp/proto/assets/2925672/cfde835b-2c5b-4605-aef4-d83a1a4acec2)

This was originally reported by @fabriguespe here: https://github.com/xmtp/xmtp-js/issues/489

### Steps to reproduce the bug

Use the JS or React SDK in a browser with source maps enabled

**Comment by tuddman** [comment]
@rygine can you confirm whether this has been resolved or is still a valid issue?  Or can this be closed as a transient build issue?

**Comment by rygine** [comment]
@fabriguespe are you still experiencing this issue?

**Comment by tuddman** [comment]
Closing as stale/transient.   If you are still experiencing this issue, feel free to reopen.
