### ISSUE TITLE
Proto definitions for xmtpv3 device contact bundles/pre-keys

### ISSUE THREAD

**Issue by richardhuaaa** [xmtp/proto#81]
Edit: michaelx11
1) Get xmtpv3 protos into `xmtp-proto` generation step and reference them in `libxmtp-core`
2) Create initial definitions for device contact bundles and pre-keys

**Comment by michaelx11** [comment]
Claiming this task, at least for 1) where I'll get us set up with the buf schema registry that @neekolas set up for the Rust<>Swift React Native effort.

**Comment by michaelx11** [comment]
Confirmed that any changes to `xmtp/proto#xmtpv3` will be pulled in and generated in `libxmtp/crates/xmtp-proto` automatically

**Comment by michaelx11** [comment]
https://github.com/xmtp/proto/pull/82

**Comment by michaelx11** [comment]
closing as we have initial definitions + e2e protobuf examples for libxmtp: https://github.com/xmtp/libxmtp/pull/89
